---
# tasks file for TP_INI

 - name: "Crear directorio"
   ansible.builtin.file:
     path: "/tmp/Grupo"
     state: directory 
     owner: vagrant
     mode: "0755"

 - name: "Crear txt file"
   ansible.builtin.file:
     path: "/tmp/Grupo/datos.txt"
     state: touch
     mode: "0644"





